.PHONY: clean All

All:
	@echo "----------Building project:[ suspension - Debug ]----------"
	@cd "suspension" && "$(MAKE)" -f  "suspension.mk"
clean:
	@echo "----------Cleaning project:[ suspension - Debug ]----------"
	@cd "suspension" && "$(MAKE)" -f  "suspension.mk" clean
